language: objective-c
osx_image: xcode8.3

env:
    global:
    - PROJECT=Tribulus.xcodeproj
    - IOS_FRAMEWORK_SCHEME="Tribulus"
    - IOS_SDK=iphonesimulator10.3.1
    
    matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 7"     SCHEME="$IOS_FRAMEWORK_SCHEME"
    
notifications:
    slack: travis-rosberry:$SLACK_NOTIFY_TOKEN
    email: false
    
before_script:
  - npm install -g conventional-changelog-cli &>/dev/null


before_deploy:
  - brew install jshon
  - export BODY=$(jshon -s "$(cat CHANGELOG.md)")

script: 
  - set -o pipefail
  - > 
      xcodebuild
      -project "$PROJECT"
      -scheme "$IOS_FRAMEWORK_SCHEME"
      -destination "$DESTINATION"
      -enableCodeCoverage YES 
      build test | xcpretty -c --test --color

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF ios
  - sh changelog.sh
  
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  body: ${BODY}
  edge: true
  on:
    tags: true

