
language: objective-c
osx_image: xcode8.3

env:
    global:
    - WORKSPACE=Tribulus.xcworkspace
    - IOS_FRAMEWORK_SCHEME="Tribulus"
    - IOS_SDK=iphonesimulator10.3.1
    matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 7"     SCHEME="$IOS_FRAMEWORK_SCHEME"
    
notifications:
    slack: travis-rosberry:MzKmgUnDtHBzXZOTWSuTcB7M
    email: false
    
before_script:
  gem install github_changelog_generator

script: 
  - set -o pipefail
  - > 
      xcodebuild
      -workspace "$WORKSPACE"
      -scheme "$IOS_FRAMEWORK_SCHEME"
      -destination "$DESTINATION"
      -enableCodeCoverage YES build test | xcpretty -c --test --color

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF ios
  
deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
