language: objective-c
osx_image: xcode8.3

env:
    global:
    - PROJECT=Tribulus.xcodeproj
    - IOS_FRAMEWORK_SCHEME="Tribulus"
    - IOS_SDK=iphonesimulator10.3.1
    matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 7"     SCHEME="$IOS_FRAMEWORK_SCHEME"
    
notifications:
    slack: travis-rosberry:MzKmgUnDtHBzXZOTWSuTcB7M
    email: false
    
before_script:
  npm install -g conventional-changelog-cli

script: 
  - set -o pipefail
  - > 
      xcodebuild
      -project "$PROJECT"
      -scheme "$IOS_FRAMEWORK_SCHEME"
      -destination "$DESTINATION"
      -enableCodeCoverage YES build test | xcpretty -c --test --color

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF ios
  - git checkout master
  - conventional-changelog -i CHANGELOG.md -s -r 0
  #- github_changelog_generator -t $CHANGELOG_GITHUB_TOKEN
  - cat CHANGELOG.md
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis"
  - git add CHANGELOG.md
  - git commit -a -m "Travis build $TRAVIS_BUILD_NUMBER [ci skip]"
  - git remote set-url origin https://$GITHUB_OAUTH_TOKEN@github.com/DmitryFrishbuter/Tribulus.git
  - git branch
  - git push -u origin master --follow-tags
  
deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
