
language: objective-c
osx_image: xcode8

env:
    global:
    - WORKSPACE=Tribulus.xcworkspace
    - IOS_FRAMEWORK_SCHEME="Tribulus"
    - IOS_SDK=iphonesimulator10.0
    matrix:
    - DESTINATION="OS=10.0,name=iPhone 7"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"

script: 
  - set -o pipefail
  - xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" build test | xcpretty -c --test --color
